name = "peters-blog"

compatibility_date = "2024-04-01"
compatibility_flags = ['nodejs_compat']
main = "src/index.ts"
minify = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "peters-blog"
database_id = "91df5ff6-28ac-419a-a283-8ec31ec72106"